<div id="custom-component"  data-bind="scope: 'custom-tutorial'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "#custom-component": {
        "Magento_Ui/js/core/app": {
            "components": {
                "custom-tutorial": {
                    "component" : "Lobbster_Knock/js/customScript",
                    "template" : "Lobbster_Knock/customtext"
                }
            }
        }
    }
}
</script>
